import { useState } from "react";
import { FileText, Sparkles, Download, ChevronRight, Eye, Plus, Search, Database } from "lucide-react";
import { PageHeader } from "@/components/shared/PageHeader";
import { Card } from "@/components/ui/Card";
import { Badge } from "@/components/ui/Badge";
import { Button } from "@/components/ui/Button";
import { Input } from "@/components/ui/Input";
import { Avatar } from "@/components/shared/Avatar";
import { Dialog } from "@/components/ui/Dialog";
import { useToast } from "@/app/providers/ToastProvider";
import { useNavigation } from "@/app/navigation";
import { reportTemplates, generatedReports, knowledgeBase } from "@/mocks/reports";
import { formatCurrency, formatDate } from "@/lib/format";
import { cn } from "@/lib/utils";

export function ReportsPage() {
  const { toast } = useToast();
  const { setPage } = useNavigation();
  const [tab, setTab] = useState<"reports" | "templates" | "kb">("reports");
  const [previewOpen, setPreviewOpen] = useState(false);
  const [search, setSearch] = useState("");

  return (
    <div className="px-8 py-7 max-w-[1480px] mx-auto">
      <PageHeader
        title="Reports & Knowledge"
        subtitle="Generate client-ready reports, manage firm playbooks, and search internal knowledge"
        actions={
          <>
            <Button variant="outline" size="md" leftIcon={<Sparkles className="h-4 w-4" />} onClick={() => setPage("copilot")}>
              Open Copilot
            </Button>
            <Button size="md" leftIcon={<Plus className="h-4 w-4" />} onClick={() => setPreviewOpen(true)}>
              Generate report
            </Button>
          </>
        }
      />

      <div className="flex items-center gap-1 border-b border-ink-150 mb-5">
        <TabBtn label={`Generated (${generatedReports.length})`} active={tab === "reports"} onClick={() => setTab("reports")} />
        <TabBtn label={`Templates (${reportTemplates.length})`} active={tab === "templates"} onClick={() => setTab("templates")} />
        <TabBtn label="Knowledge base" active={tab === "kb"} onClick={() => setTab("kb")} />
      </div>

      {tab === "reports" && (
        <Card padded={false}>
          <table className="w-full text-[13px]">
            <thead>
              <tr className="text-[11px] font-semibold uppercase tracking-wider text-ink-400 border-b border-ink-150 bg-ink-50">
                <th className="text-left font-semibold px-5 py-2.5">Report</th>
                <th className="text-left font-semibold py-2.5">Client</th>
                <th className="text-left font-semibold py-2.5">Generated by</th>
                <th className="text-left font-semibold py-2.5">Status</th>
                <th className="text-right font-semibold py-2.5">Savings</th>
                <th className="text-right font-semibold py-2.5">When</th>
                <th className="pr-5 py-2.5" />
              </tr>
            </thead>
            <tbody>
              {generatedReports.map((r) => (
                <tr key={r.id} className="border-b border-ink-100 last:border-0 hover:bg-ink-50 transition-colors">
                  <td className="px-5 py-3">
                    <div className="flex items-center gap-2.5">
                      <div className="h-8 w-8 rounded bg-brand-100 text-brand-700 flex items-center justify-center">
                        <FileText className="h-4 w-4" />
                      </div>
                      <div>
                        <div className="text-[13px] font-medium text-ink-900">{r.templateName}</div>
                        <div className="text-[11px] text-ink-400">{r.id}</div>
                      </div>
                    </div>
                  </td>
                  <td className="py-3 text-ink-700">{r.clientName}</td>
                  <td className="py-3">
                    <div className="flex items-center gap-2">
                      <Avatar name={r.generatedBy} size="xs" />
                      <span className="text-[12px] text-ink-700">{r.generatedBy.split(" ")[0]}</span>
                    </div>
                  </td>
                  <td className="py-3">
                    <Badge tone={r.status === "delivered" ? "success" : r.status === "in-review" ? "warn" : "neutral"} dot>
                      {r.status === "delivered" ? "Delivered" : r.status === "in-review" ? "In review" : "Draft"}
                    </Badge>
                  </td>
                  <td className="py-3 text-right">
                    {r.estimatedSavings ? (
                      <span className="font-mono tabular text-success-ink">+{formatCurrency(r.estimatedSavings, { compact: true })}</span>
                    ) : (
                      <span className="text-ink-300">—</span>
                    )}
                  </td>
                  <td className="py-3 text-right text-[12px] text-ink-500">{formatDate(r.generatedAt, { format: "rel" })}</td>
                  <td className="pr-5 py-3 text-right">
                    <div className="inline-flex items-center gap-1">
                      <Button size="sm" variant="ghost" leftIcon={<Eye className="h-3.5 w-3.5" />} onClick={() => setPreviewOpen(true)}>
                        Preview
                      </Button>
                      <Button size="sm" variant="ghost" leftIcon={<Download className="h-3.5 w-3.5" />} onClick={() => toast({ kind: "success", title: "Download started", description: `${r.templateName} · ${r.clientName}` })}>
                        PDF
                      </Button>
                    </div>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </Card>
      )}

      {tab === "templates" && (
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
          {reportTemplates.map((t) => (
            <Card key={t.id} padded interactive className="flex flex-col">
              <div className="flex items-center gap-2 mb-3">
                <div className="h-8 w-8 rounded bg-accent-violetBg flex items-center justify-center">
                  <FileText className="h-4 w-4 text-accent-violet" />
                </div>
                <Badge tone="neutral">{t.category}</Badge>
              </div>
              <h3 className="text-h3 text-ink-900 mb-1.5">{t.name}</h3>
              <p className="text-small text-ink-500 leading-relaxed flex-1">{t.description}</p>
              <div className="flex items-center justify-between mt-4 text-[11.5px] text-ink-500">
                <span>{t.pages} pages · {t.sampleAudience}</span>
                <Button size="sm" variant="ghost" rightIcon={<ChevronRight className="h-3 w-3" />} onClick={() => setPreviewOpen(true)}>
                  Use
                </Button>
              </div>
            </Card>
          ))}
        </div>
      )}

      {tab === "kb" && (
        <div>
          <div className="mb-4">
            <Input
              value={search}
              onChange={(e) => setSearch(e.target.value)}
              placeholder="Search firm playbooks, compliance guides, and templates…"
              leftIcon={<Search className="h-4 w-4" />}
              className="max-w-[520px]"
            />
          </div>
          <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
            {knowledgeBase
              .filter((a) => !search || a.title.toLowerCase().includes(search.toLowerCase()))
              .map((a) => (
                <Card key={a.id} padded interactive>
                  <div className="flex items-start gap-3">
                    <div className="h-9 w-9 rounded bg-ink-100 flex items-center justify-center text-ink-700 shrink-0">
                      <Database className="h-4 w-4" />
                    </div>
                    <div className="min-w-0 flex-1">
                      <Badge tone="info" size="sm">{a.category}</Badge>
                      <h3 className="text-h3 text-ink-900 mt-2 mb-1.5">{a.title}</h3>
                      <p className="text-small text-ink-500 leading-relaxed">{a.excerpt}</p>
                      <div className="flex items-center gap-2 mt-3 text-[11px] text-ink-500">
                        <span>{a.source}</span>
                        <span>·</span>
                        <span>{a.tags.join(", ")}</span>
                      </div>
                    </div>
                  </div>
                </Card>
              ))}
          </div>
        </div>
      )}

      <Dialog
        open={previewOpen}
        onOpenChange={setPreviewOpen}
        title="Annual Tax Planning Report — Halcyon Roastery & Co."
        description="14 pages · Generated by AI · Ready for partner review"
        size="xl"
        footer={
          <>
            <Button variant="ghost" onClick={() => setPreviewOpen(false)}>Close preview</Button>
            <Button variant="outline" leftIcon={<Download className="h-4 w-4" />}>
              Download PDF
            </Button>
            <Button onClick={() => { setPreviewOpen(false); toast({ kind: "success", title: "Sent for partner review", description: "Adnan Karim notified" }); }}>
              Submit for review
            </Button>
          </>
        }
      >
        <ReportPreview />
      </Dialog>
    </div>
  );
}

function TabBtn({ label, active, onClick }: { label: string; active: boolean; onClick: () => void }) {
  return (
    <button
      onClick={onClick}
      className={cn(
        "h-10 px-4 text-[13.5px] font-medium border-b-2 -mb-px transition-colors",
        active ? "border-brand-500 text-brand-700" : "border-transparent text-ink-500 hover:text-ink-700",
      )}
    >
      {label}
    </button>
  );
}

function ReportPreview() {
  return (
    <div className="bg-ink-50 rounded-lg p-6 border border-ink-150">
      <div className="bg-paper rounded-lg shadow-sm p-8 max-w-[720px] mx-auto">
        <div className="flex items-start justify-between mb-6 pb-5 border-b border-ink-150">
          <div>
            <div className="h-9 w-9 rounded-md bg-ai-gradient flex items-center justify-center text-white font-bold mb-3">A</div>
            <div className="text-micro uppercase text-ink-400">Aragon Advisors · 2024 Annual Tax Plan</div>
            <h2 className="text-h1 text-ink-900 mt-1">Halcyon Roastery & Co.</h2>
            <div className="text-[12.5px] text-ink-500 mt-1">Prepared for Adrián Mendez, Owner · Mar 2024</div>
          </div>
          <div className="text-right">
            <div className="text-micro uppercase text-ink-400 mb-1">Projected savings</div>
            <div className="text-display-xl font-display font-semibold text-success-ink tabular">$96,400</div>
          </div>
        </div>

        <div className="text-h3 text-ink-900 mb-3">Executive summary</div>
        <p className="text-small text-ink-700 leading-relaxed mb-5">
          Halcyon's projected 2024 federal and state liability is{" "}
          <span className="font-semibold">$412K</span>. After implementing the 5 strategies recommended by AI-powered analysis
          of your bookkeeping, prior returns, payroll, and entity structure, projected liability falls to{" "}
          <span className="font-semibold text-success-ink">$315.6K</span> — a savings of{" "}
          <span className="font-semibold text-success-ink">$96,400</span>. Implementation requires owner sign-off on three items
          and minimal disruption to operations.
        </p>

        <div className="text-h3 text-ink-900 mb-3">Recommended strategies</div>
        <ol className="space-y-2.5 mb-5">
          {[
            { t: "Reduce S-Corp salary to reasonable comp benchmark", s: 28_400 },
            { t: "Implement accountable plan for owner-paid expenses", s: 16_200 },
            { t: "Establish solo 401(k) with profit-sharing", s: 22_500 },
            { t: "Cost segregation study on $2.4M property", s: 18_900 },
            { t: "Reclassify meals to 50% deductible", s: 10_400 },
          ].map((s, i) => (
            <li key={i} className="flex items-center justify-between border-b border-ink-100 pb-2.5">
              <span className="text-[13px] text-ink-900">
                <span className="font-semibold tabular mr-2">{i + 1}.</span>
                {s.t}
              </span>
              <span className="text-[13px] font-mono tabular text-success-ink font-semibold">+{formatCurrency(s.s)}</span>
            </li>
          ))}
        </ol>

        <div className="grid grid-cols-3 gap-3 mb-5">
          <div className="border border-ink-150 rounded-md p-3 bg-ink-50 text-center">
            <div className="text-micro uppercase text-ink-400 mb-1">Baseline</div>
            <div className="text-[15px] font-semibold tabular text-ink-900">$412,000</div>
          </div>
          <div className="border border-ink-150 rounded-md p-3 bg-ink-50 text-center">
            <div className="text-micro uppercase text-ink-400 mb-1">Optimized</div>
            <div className="text-[15px] font-semibold tabular text-info-ink">$315,600</div>
          </div>
          <div className="border border-success/20 rounded-md p-3 bg-success-bg text-center">
            <div className="text-micro uppercase text-success-ink mb-1">Savings</div>
            <div className="text-[15px] font-semibold tabular text-success-ink">$96,400</div>
          </div>
        </div>

        <div className="text-h3 text-ink-900 mb-2">Implementation checklist</div>
        <ul className="space-y-1.5 text-small text-ink-700">
          <li>· File Form 2553 confirmation with IRS — Mar 15</li>
          <li>· Adopt accountable plan resolution at next board meeting</li>
          <li>· Open solo 401(k) with provider — TPA selected</li>
          <li>· Engage cost segregation engineering firm — Q1</li>
          <li>· Update meals categorization in QuickBooks · communicate to bookkeeper</li>
        </ul>

        <div className="mt-6 pt-4 border-t border-ink-150 text-[10.5px] text-ink-400 italic">
          This report was generated by Aragon's AI analysis engine using firm-approved playbooks. All strategies require advisor
          and partner sign-off before delivery to client.
        </div>
      </div>
    </div>
  );
}
